# Example only — do NOT commit real secrets
# Copy these to Streamlit Cloud's Secrets (Settings → Secrets)

# Optional: specify which model to load
MODEL_PATH = "models/xgboost_model.pkl"           # or "models/random_forest_model.pkl"
FEATURE_NAMES_PATH = "models/feature_names.pkl"

# Optional: URLs to download models if not present (must be public or signed URLs)
# MODEL_URL = "https://example.com/path/to/xgboost_model.pkl"
# FEATURE_NAMES_URL = "https://example.com/path/to/feature_names.pkl"

# Alpha Vantage API key for reliable real-time data on Streamlit Cloud
# Get free API key from: https://www.alphavantage.co/support/#api-key
# Free tier: 5 API calls per minute, 500 per day
ALPHA_VANTAGE_API_KEY = "{{YOUR_ALPHA_VANTAGE_API_KEY}}"

# Optional: API keys (if you later enable live news/macro providers)
# NEWS_API_KEY = "{{NEWS_API_KEY}}"
# FRED_API_KEY = "{{FRED_API_KEY}}"

